return {

    { dir = '~/src/nv/bhs/' },

    { 'NvChad/nvim-colorizer.lua',        config = true, lazy = false,                                  opts = {}, enabled = true, },
    { 'rktjmp/lush.nvim' },
    { 'uga-rosa/ccc.nvim',                opts = {}, },


    { 'Skalyaeve/a-nvim-theme',           lazy = true, },
    { 'projekt0n/caret.nvim',             lazy = true, },
    { 'challenger-deep-theme/vim',        lazy = true, },
    { 'Everblush/nvim',                   lazy = true,   name = 'everblush' },
    { 'EdenEast/nightfox.nvim',           lazy = true, },
    { 'rose-pine/neovim',                 lazy = true,   name = 'rose-pine' },
    -- --{ dir = '~/.config/nvim/lua/plugins/rosepine/', lazy = true,},
    { 'LunarVim/horizon.nvim',            lazy = true,   name = 'horizon' },
    { 'nyoom-engineering/oxocarbon.nvim', lazy = true, },
    { 'Mofiqul/vscode.nvim',              lazy = true, },
    { 'marko-cerovac/material.nvim',      lazy = true, },
    { 'lighthaus-theme/vim-lighthaus',    lazy = true, },
    { 'junegunn/seoul256.vim',            lazy = true, },
    { 'josegamez82/starrynight',          lazy = true, },
    { 'felipeagc/fleet-theme-nvim',       lazy = true,   name = 'fleet' },
    { 'rockerBOO/boo-colorscheme-nvim',   lazy = true, },
    { 'maxmx03/fluoromachine.nvim',       lazy = true,   opts = { theme = 'flouromachine' } },
    { 'folke/tokyonight.nvim',            lazy = true, },
    { 'sainnhe/sonokai',                  lazy = true, },
    { 'sainnhe/edge',                     lazy = true, },
    { 'monsonjeremy/onedark.nvim',        lazy = true, },
    { 'eldritch-theme/eldritch.nvim',     lazy = true, },
    { 'zootedb0t/citruszest.nvim',        lazy = true, },
    { 'ishan9299/modus-theme-vim',        lazy = true, }, --{'miikanissi/modus-themes.nvim',opts={transparent=true},},
    { 'kevinm6/kurayami.nvim',            lazy = true, },
    { 'samharju/synthweave.nvim',         lazy = true, },
    { 'scottmckendry/cyberdream.nvim',    lazy = true, },
    { 'alexmozaidze/palenight.nvim',      lazy = true, },
    { 'Mofiqul/adwaita.nvim',             lazy = true, },
    { 'shaunsingh/moonlight.nvim',        lazy = true, },
    { 'bkegley/gloombuddy',               lazy = true,   dependencies = { 'tjdevries/colorbuddy.vim' }, },
    { 'FelipeIzolan/lipoide.nvim',        lazy = true, },
    { 'bgwdotdev/gleam-theme-nvim',       lazy = true, },
    { 'Shadorain/shadotheme',             lazy = true, },
    { 'doums/darcula',                    lazy = true, },
    { 'Mofiqul/dracula.nvim',             lazy = true, },
    { 'Love-Pengy/lillilac.nvim',         lazy = true, },
    { 'catppuccin/nvim',                  lazy = true,   name = 'catppuccin' },
    { 'comfysage/evergarden',             lazy = true, },

    {
        'folke/styler.nvim',
        enabled = true,
        opts = {
            themes = {
                -- markdown = { colorscheme = 'citruszest' },
                c = { colorscheme = 'fleet' },
                cpp = { colorscheme = 'vscode' },
                python = { colorscheme = 'everblush' },
            },
        },
    },

}
